### ISSUE TITLE
Text.capitalize($str) only capitalizes first letter.

### ISSUE THREAD

**Issue by ghost** [AegisFramework/Oregano#3]
Text.capitalize("hello world");
outputs =>
"Hello world"
:| no idea why.
(using the aegis.js provided | same result on minified version)

**Comment by Hyuchia** [comment]
You are right, this was a bug, it had been a while since I updated this since most of the repositories are now in the [Aegis Framework Organization](https://github.com/AegisFramework). I just made a [new release](https://github.com/Hyuchia/AegisTemplate/releases/latest) that should fix this, the release adds some big changes so if you need any help you can contact me by email as well. :+1:

**Comment by ghost** [comment]
thanks :)
